apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  ports:
  - port: 6333
  selector:
    app: qdrant
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  ports:
  - port: 7687
  selector:
    app: neo4j
